# Generated by Django 4.2.2 on 2024-07-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_send', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата отправки')),
                ('attempt_status', models.CharField(blank=True, choices=[('Y', 'Успешно'), ('N', 'Ошибка')], max_length=1, null=True, verbose_name='Статус')),
                ('answer_server', models.TextField(blank=True, null=True, verbose_name='Ответ сервера')),
            ],
            options={
                'verbose_name': 'Лог',
                'verbose_name_plural': 'Логи',
                'ordering': ('id',),
                'permissions': [('can_view_logs', 'can view logs')],
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('start_date', models.DateTimeField(verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата окончания')),
                ('periodicity', models.CharField(blank=True, choices=[('D', 'Раз в день'), ('W', 'Раз в неделю'), ('M', 'Раз в месяц')], default='D', max_length=1, null=True, verbose_name='Периодичность')),
                ('mailing_status', models.CharField(blank=True, choices=[('C', 'Создана'), ('R', 'Запущена'), ('S', 'Остановлена'), ('E', 'Завершена')], default='C', max_length=1, null=True, verbose_name='Статус')),
                ('client', models.ManyToManyField(to='client.client', verbose_name='Клиенты')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
                'ordering': ('id',),
                'permissions': [('can_view_mailings', 'can view mailings'), ('can_check_status_mailings', 'can check status mailings')],
            },
        ),
    ]
